<?php 
namespace App\Larabookir;
use  Illuminate\Routing\UrlGenerator as base;;

class UrlGenerator extends base
{
	protected $appendUnNamedParametersToQuery=true;

	public function route($name, $parameters = [], $absolute = true)
	{
		$parameters = (array)$parameters;

		if (!key_exists('lang', $parameters)) {
			$parameters['lang'] = \App::getLocale();
			$this->appendUnNamedParametersToQuery=false;
		}

		return parent::route($name, $parameters, $absolute); // TODO: Change the autogenerated stub
	}

	/**
	 * Add a query string to the URI.
	 *
	 * @param  string  $uri
	 * @param  array  $parameters
	 * @return mixed|string
	 */
	protected function addQueryString($uri, array $parameters)
	{
		// If the URI has a fragment, we will move it to the end of this URI since it will
		// need to come after any query string that may be added to the URL else it is
		// not going to be available. We will remove it then append it back on here.
		if (! is_null($fragment = parse_url($uri, PHP_URL_FRAGMENT))) {
			$uri = preg_replace('/#.*/', '', $uri);
		}
		if($this->appendUnNamedParametersToQuery)
			$uri .= $this->getRouteQueryString($parameters);

		return is_null($fragment) ? $uri : $uri."#{$fragment}";
	}

	public function to($path, $extra = [], $secure = null)
	{

		if(!starts_with($path,['http','www','.','//','#', 'mailto:', 'tel:',])){

			$extra=(array) $extra;
			if (!key_exists('lang', $extra))
				$path = \App::getLocale().left_ch($path);
			else {
				$path = $extra['lang'] . left_ch($path);
				unset($extra['lang']);
			}
		}

		return parent::to($path, $extra, $secure); // TODO: Change the autogenerated stub
	}


}